Color Example + Android Animation Improvement
cactuslab/capacitor-native-navigation pull request #13
Opened 2024-12-03 04:04 UTC by TomCarey

- Added an example for theming each screen on transition
- Improved status bar color changes by introducing an animated value

2024-12-03 04:26 UTC, TomCarey commented
Watching the animations frame by frame I'm noticing there is perhaps an over complication where we might not be needing to set the status bar color at all which, if true, would allow the animator for the navigation to be the driving factor so that transitions with or without animation look perfect.

2025-01-29 21:41 UTC, karlvr requested changes

2025-01-29 21:41 UTC, karlvr commented on packages/example/src/js/race/PushTheming.tsx
> +const SetBodyAttribute: React.FC<{ attribute: string; value: string | null }> = ({ attribute, value }) => {
Let's add some documentation to this component to explain what this is an example of, and some docs through the code to explain.

2025-01-29 21:41 UTC, karlvr commented on packages/example/src/js/race/PushTheming.tsx
> +		<Route path="red" element={<PushRed />} />
Fix indentation.

2025-01-29 21:41 UTC, karlvr commented on packages/example/src/js/race/PushTheming.tsx
> +		<SetBodyAttribute attribute="theme" value="red" />
Fix indentation.

2025-01-29 21:41 UTC, karlvr commented on packages/example/src/js/race/PushTheming.tsx
> +		navigate('/race/push-theming/red')
Should this still be in race?

2025-01-29 21:41 UTC, karlvr commented on packages/example/src/js/race/PushTheming.tsx
> +					color: '#b0c9ffff',
The alpha isn't significant.

2025-01-29 21:41 UTC, karlvr commented on packages/example/src/js/race/PushTheming.tsx
> +	useEffect(() => {
Don't need state. Combine into one `useEffect` with `updateView`.

2025-01-29 21:41 UTC, karlvr commented on packages/example/src/js/app.css
> +body[data-theme="red"] {
Can we move these to a `PushTheming.css` and import from `PushTheming.tsx`

2025-01-31 03:53 UTC, karlvr requested changes

2025-01-31 03:53 UTC, karlvr commented on packages/example/src/js/examples/TallContent.tsx
> +import React, { useEffect } from 'react'
These new imports are pretty suss dude.

2025-01-31 03:53 UTC, karlvr commented on packages/example/src/js/app.css
> +}
Why you remove the newline at the end of this file?

2025-01-31 03:58 UTC, karlvr approved these changes

2025-01-31 03:58 UTC, merged